### ISSUE TITLE
Feature: Run fixer without automatically creating cache

### ISSUE THREAD

**Issue by assertchris** [mnapoli/pretty#1]
Don't know about phpcs, but cs-fixer will automatically create the cache file, if none exists, unless run with a `--using-cache`. If someone switches from one fixer to the other; files like this would become mess...

**Comment by mnapoli** [comment]
There would be one tool (phpcs or php-cs-fixer) per project, so it's fine if a cache file is created, it will be only the one that makes sense.

I think the README is not clear enough ^^ Basically if I checkout a project X or Y to contribute, I don't want to figure out which tool to run, so I just run `pretty` and it will figure out what to run. But it always runs the same thing for one project.

I maybe I completely missed what you were saying ^^

**Comment by mnapoli** [comment]
I have added a `pretty ci` option in #3, that disables the cache because it's not necessary in CI environment.
