### ISSUE TITLE
Support local (vendor) installations of phpcs and php-cs-fixer

### ISSUE THREAD

**Issue by mnapoli** [mnapoli/pretty#10]
Pretty runs tools installed globally.

It would be great if it worked with tools (phpcs/php-cs-fixer) installed locally in the project, in the `vendor/` directory.

**Comment by jessevdp** [comment]
I don't know exactly how composer works . . . but I find it odd that I even need to install `phpcs` myself. When I already install `pretty`. Is there no way `phpcs` could be a dependency of Pretty itself? So users don't need to install this tool themselves.

**Comment by mnapoli** [comment]
The thing is that pretty supports both CodeSniffer and php-cs-fixer (both are different tools).

It's either one or the other. Which is why it doesn't make sense to require both.

I tend to install pretty globally instead (`composer global require mnapoli/pretty`) and then it's available everywhere. Then each project can require phpcs.

**Comment by glensc** [comment]
just add `vendor/bin` to paths to check.

as your tool uses `which` and exec, add somewhere:

```php
putenv(join("", array("PATH=vendor/bin", PATH_SEPARATOR, getenv("PATH"))));
// or
putenv(join("", array("PATH=", getenv("PATH"), PATH_SEPARATOR, "vendor/bin")));
```

**Comment by staabm** [comment]
> ```
> putenv(join("", array("PATH=vendor/bin", PATH_SEPARATOR, getenv("PATH"))));
> ```

just stole your code and created a PR with it, as it worked locally for me:
https://github.com/mnapoli/pretty/pull/17
