### ISSUE TITLE
Result \array_key_exist is different to prettyci.com

### ISSUE THREAD

**Issue by alexander-schranz** [mnapoli/pretty#19]
When using Symfony rules the local will add the slash \array_key_exist but the CI want that you remove it. It seems like the CI is using an older version of the php-cs-fixer.

**Comment by mnapoli** [comment]
Hi! The CI is indeed using the latest stable version, and upgrading it might break backward compatibility for some projects so I am still pondering the upgrade.

However, you can choose which version to use via a `.prettyci.composer.json` file, and in there require your desired version of php-cs-fixer. Here are more details: https://prettyci.com/documentation#using-a-custom-standard

**Comment by alexander-schranz** [comment]
@mnapoli can you say which version is currenty locked on prettyci.com ?

**Comment by mnapoli** [comment]
@alexander-schranz it is v2.14.0

**Comment by alexander-schranz** [comment]
@mnapoli thank you! From my side this issue can then be closed.
