### ISSUE TITLE
No configuration file found

### ISSUE THREAD

**Issue by RinkAttendant6** [mnapoli/pretty#8]
I get this error when running `pretty`:
> No configuration file found, running PHP CodeSniffer with PSR-2

I have a `.phpcs.xml` file in the project and I have also tried renaming it to `.phpcs.xml.dist` but I get the same result and it defaults to PSR-2. When I execute phpcs using `vendor/bin/phpcs .` it runs fine.

Is there something else I am missing?

**Comment by mnapoli** [comment]
Thanks for the report.

The tool is currently looking for those files without the leading `.`: https://github.com/mnapoli/pretty/blob/master/pretty#L51 (this is how it is documented in CodeSniffer's wiki).

However the code seem to accept those files:

https://github.com/squizlabs/PHP_CodeSniffer/blob/6172062f09eccea2c851cbc11daad137ebe52f98/src/Config.php#L343-L346

```php
            $defaultFiles = [
                '.phpcs.xml',
                'phpcs.xml',
                '.phpcs.xml.dist',
                'phpcs.xml.dist',
            ];
```

So it seems to be only a matter of adding them in the `if`, would you be able to send a pull request? If not I can do this myself, probably this week-end.
